spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3316/auth_db
    username: auth_admin
    password: auth_admin
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: validate
server:
  port: 8081